spring:
  datasource:
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: true
  jpa:
    hibernate:
      ddl-auto: validate